### ISSUE TITLE
homebrew install command fails

### ISSUE THREAD

**Issue by o-az** [raystack/stencil#175]
following the official installation instruction:

https://github.com/raystack/stencil/blob/2213f4b9120a8f8072d60f01f2af4e1e6f20d758/docs/docs/installation.md?plain=1#L21

![CleanShot 2024-06-04 at 21 19 34](https://github.com/raystack/stencil/assets/23618431/a19512cd-4838-4658-a930-5810cd4f802e)

**Comment by turtleDev** [comment]
Hi @o-az 

The correct syntax for setting up a tap is
```bash
$ brew tap raystack/tap
```

To install directly use:
```bash
$ brew install raystack/tap/stencil
```

Let us know if you run into any further issues.

**Comment by ravisuhag** [comment]
@o-az Fixed the download issue. Should be working now.
